name: workspace deployment

on:
  push:
    branches: [ publish_branch ]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Synapse workspace
        uses: azure/synapse-workspace-deployment@release-1.0
        with:
          TargetWorkspaceName: 'testlh'
          TemplateFile: './path/to/TemplateForWorkspace.json'
          ParametersFile: './path/to/TemplateParametersForWorkspace.json'
          OverrideArmParameters: './path/to/parameters.yaml'
          environment: 'Azure Public'
          resourceGroup: 'testing09'
          clientId: ${{ secrets.CLIENTID }}
          clientSecret: ${{ secrets.CLIENTSECRET }}
          subscriptionId: 'e64e16eb-492c-4f71-8676-e1dd809a75d7'
          tenantId: 'tenantId'
          DeleteArtifactsNotInTemplate: 'true'
          managedIdentity: 'False'
